sudo: required
services:
  - docker

before_install:
  - docker build  -t suunyzhou/docker-learning-fontend -f Dockerfile.dev .

script:
  - docker run -e CI=true suunyzhou/docker-learning-fontend npm run test

language: generic 
